---
title: "Latihan2_123190126"
author: "Kevin Bimo Saputro"
date: "9/16/2021"
output:
  word_document: default
  html_document: default
  pdf_document: default
---

#### Nomor 1

```
str(murders);
```

###### 'data.frame':	51 obs. of  5 variables:
###### $ abb       : chr  "AL" "AK" "AZ" "AR" ...")
 
###### $ state     : chr  "Alabama" "Alaska" "Arizona" "Arkansas" ...

###### $ region    : Factor w/ 4 levels "Northeast","South",..: 2 4 4 2 4 4 1 2 2 2 ...
###### $ population: num  4779736 710231 6392017 2915918 37253956 ...
###### $ total     : num  135 19 232 93 1257 ...


##### Pilihan yang benar adalah C. Data berisi nama Negara bagian, singkatan dari nama negara bagian, wilayah negara bagian, dan populasi negara bagian serta jumlah total pembunuhan pada tahun 2010. karena sesuai dengan hasil tampilan setelah menulis ```str(murders)``` di console dan menekan enter makan hasil yang muncul sama seperti apa yang dikatakan oleh pilihan C


#### Nomor 2

```
> names(murders)
[1] "state"      "abb"        "region"     "population" "total"
```
##### Nama kolom yang digunakan : state, abb, region, population, dan total.


#### Nomer 3

```
> a <- murders$abb
> class(a)
[1] "character"
```
##### abb akan tersimpan diclass a bertipe data char

#### Nomer 4

```
> b <- murders[[2]]
> class(b)
[1] "character"
```
##### Mengekstrak singkatan negara dan menyimpannya pada variabel b.

```
> b == a
 [1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
[16] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
[31] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
[46] TRUE TRUE TRUE TRUE TRUE TRUE
```
##### hasil perbandingannya semuanya TRUE maka kedua variabel memiliki data yang sama

#### Nomor 5

##### Menentukan jumlah region yang dimiliki oleh dataset.
```
> length(levels(murders$region))
[1] 4
```
#### Nomor 6

##### Menampilkan tabel yang berisi jumlah state pada tiap region.
```
> table(murders$region)

    Northeast         South North Central          West 
            9            17            12            13 
```